import { Vedeto, AvailabilitySlot } from './types'

const PRICING = [
  {
    id: 'p1',
    name: 'Show Clásico',
    duration: '45 - 50 min',
    price: 140000,
    description: 'Tres apariciones con vestuario distinto. Santiago (comunas exteriores con recargo)',
    features: [
      'Tres salidas con vestuario distinto',
      'Movilización propia',
      'Equipo de música y luces',
      'Múltiples personajes',
      'Brindis de honor para la anfitriona',
    ],
  },
  {
    id: 'p2',
    name: 'Show con Animador',
    duration: '45 - 50 min',
    price: 200000,
    description: 'Presentación completa con maestro de ceremonias incluido para una experiencia de mayor impacto',
    features: [
      'Tres salidas con vestuario distinto',
      'Maestro de ceremonias incluido',
      'Movilización propia',
      'Equipo de música y luces',
      'Múltiples personajes',
      'Brindis de honor para la anfitriona',
    ],
  },
]

export const vedetos: Vedeto[] = [
  {
    id: '1',
    name: 'Venom',
    slug: 'venom',
    shortDescription: 'Presencia escénica imponente. Especialista en personajes de autoridad con un carisma que domina la sala desde su primera aparición.',
    fullDescription: 'Venom es uno de los artistas más solicitados del elenco Luxx. Su porte natural y su manejo del espacio escénico generan un impacto inmediato. Especializado en personajes de autoridad, construye cada aparición con precisión — vestuario, actitud y ritmo coordinados al detalle para elevar el tono de cualquier celebración.',
    image: '/vedetos/Venom/Venom0.webp',
    gallery: [
      '/vedetos/Venom/Venom0.webp',
      '/vedetos/Venom/Venom1.webp',
      '/vedetos/Venom/Venom2.webp',
    ],
    rating: 4.8,
    reviewCount: 94,
    pricing: PRICING,
    availability: generateAvailability(),
    location: 'Santiago, Chile',
    specialties: ['Militar', 'Constructor'],
    featured: true,
  },
  {
    id: '2',
    name: 'Nicolas',
    slug: 'nicolas',
    shortDescription: 'Artista de alta demanda con versatilidad escénica y un amplio registro de personajes. Cada show, una propuesta distinta.',
    fullDescription: 'Nicolás es el artista de mayor versatilidad del elenco Luxx. Su capacidad para transitar entre registros — del capitán al vaquero — con igual convicción lo convierte en la elección ideal cuando se busca variedad dentro de una misma velada. Domina el escenario con naturalidad y construye un vínculo genuino con el público.',
    image: '/vedetos/Nicolas/Nicolas0.webp',
    gallery: [
      '/vedetos/Nicolas/Nicolas0.webp',
      '/vedetos/Nicolas/Nicolas1.webp',
      '/vedetos/Nicolas/Nicolas2.webp',
    ],
    rating: 4.85,
    reviewCount: 108,
    pricing: PRICING,
    availability: generateAvailability(),
    location: 'Santiago, Chile',
    specialties: ['Policia', 'Vaquero', 'Capitan'],
    featured: true,
  },
  {
    id: '3',
    name: 'Lorenzo',
    slug: 'lorenzo',
    shortDescription: 'Performer con porte cuidado y presencia segura. Tres personajes escénicos, un solo estándar: excelencia.',
    fullDescription: 'Lorenzo es el perfil más versátil y cuidado del elenco Luxx. Su imagen es precisa — cada aparición está pensada en términos de vestuario, actitud y ritmo. Transita con igual solvencia entre el capitán, el oficial y el vaquero, adaptando el carácter del personaje al ambiente de cada evento sin perder cohesión.',
    image: '/vedetos/Lorenzo/Lorenzo0.webp',
    gallery: [
      '/vedetos/Lorenzo/Lorenzo0.webp',
      '/vedetos/Lorenzo/Lorenzo11.png',
      '/vedetos/Lorenzo/Lorenzo2.webp',
      '/vedetos/Lorenzo/Lorenzo3.webp',
      '/vedetos/Lorenzo/Lorenzo4.png',
      '/vedetos/Lorenzo/Lorenzo8.webp',
    ],
    rating: 4.9,
    reviewCount: 127,
    pricing: PRICING,
    availability: generateAvailability(),
    location: 'Santiago, Chile',
    specialties: ['Capitan', 'Policia', 'Vaquero'],
    featured: true,
  },
  {
    id: '4',
    name: 'JC El Alfa',
    slug: 'juan-carlos',
    shortDescription: 'Artista con conexión natural con el público. La energía del salón cambia desde el momento en que entra.',
    fullDescription: 'Juan Carlos es el artista que transforma la atmósfera de la sala antes de que empiece el show. Su carisma es genuino — no actúa la cercanía, la tiene. Ideal para celebraciones de cumpleaños y despedidas donde la dinámica grupal es parte del espectáculo. Se adapta con fluidez a cualquier formato.',
    image: '/vedetos/JC/JC 0.PNG',
    gallery: [
      '/vedetos/JC/JC 0.PNG',
      '/vedetos/JC/JC 1.PNG',
      '/vedetos/JC/JC 2.PNG',
      '/vedetos/JC/JC 3.PNG',
      '/vedetos/JC/JC 4.PNG',
      '/vedetos/JC/JC 5.PNG',
      '/vedetos/JC/JC 6.PNG',
      '/vedetos/JC/JC 7.PNG',
    ],
    rating: 4.75,
    reviewCount: 81,
    pricing: PRICING,
    availability: generateAvailability(),
    location: 'Santiago, Chile',
    specialties: ['Constructor', 'Militar', 'Vaquero'],
    featured: true,
  },
  {
    id: '5',
    name: 'Benjamin',
    slug: 'benjamin',
    shortDescription: 'Presencia que detiene la sala. Un perfil de alto impacto construido sobre años de escena y un manejo del espacio que pocos dominan.',
    fullDescription: 'Benjamín es el artista que convierte la entrada en el momento cumbre de la noche. Su porte, su ritmo y su capacidad de leer al público en tiempo real hacen de cada presentación un espectáculo irrepetible. Tres personajes, tres registros — todos ejecutados con la misma precisión y entrega que lo han convertido en el perfil más solicitado del elenco.',
    image: '/vedetos/Benjamin/Benjamin0.webp',
    gallery: [
      '/vedetos/Benjamin/Benjamin0.webp',
      '/vedetos/Benjamin/Benjamin1.webp',
      '/vedetos/Benjamin/Benjamin3.webp',
    ],
    rating: 4.9,
    reviewCount: 143,
    pricing: PRICING,
    availability: generateAvailability(),
    location: 'Santiago, Chile',
    specialties: ['Capitan', 'Policia', 'Constructor'],
    featured: true,
  },
  {
    id: '8',
    name: 'Jesus Polanco',
    slug: 'jesus',
    shortDescription: 'Carácter propio y carisma sin filtro. Un artista que convierte cada actuación en algo genuinamente suyo.',
    fullDescription: 'Jesús Polanco tiene algo que no se enseña: presencia natural. Su carácter directo y su capacidad de conectar con el público desde el primer segundo hacen que cada show tome una forma propia. No hay dos presentaciones iguales — y eso es exactamente lo que lo define.',
    image: '/vedetos/Jesus Polanco/Jesus 0.png',
    gallery: [
      '/vedetos/Jesus Polanco/Jesus 0.png',
      '/vedetos/Jesus Polanco/Jesus 1.png',
      '/vedetos/Jesus Polanco/Jesus 2.png',
      '/vedetos/Jesus Polanco/Jesus 3.png',
      '/vedetos/Jesus Polanco/Jesus 4.png',
      '/vedetos/Jesus Polanco/Jesus 5.png',
      '/vedetos/Jesus Polanco/Jesus 6.png',
      '/vedetos/Jesus Polanco/Jesus 7.png',
      '/vedetos/Jesus Polanco/Jesus 8.JPG',
    ],
    rating: 4.72,
    reviewCount: 63,
    pricing: PRICING,
    availability: generateAvailability(),
    location: 'Santiago, Chile',
    specialties: ['Capitan', 'Militar'],
    featured: true,
  },
  {
    id: '11',
    name: 'Paulo Cassanova',
    slug: 'paulo-cassanova',
    shortDescription: 'Estilo sofisticado y una presencia que no pasa desapercibida. Paulo convierte cada show en una experiencia de alto nivel.',
    fullDescription: 'Paulo Cassanova trae consigo una propuesta escénica distinta: elegancia calculada y una energía que sabe cuándo intensificarse y cuándo contenerse. Su versatilidad le permite adaptarse al tono de cada evento sin perder su identidad propia, generando una experiencia que combina impacto visual con una conexión genuina con el público.',
    image: '/vedetos/Paulo/Paulo 0.png',
    gallery: [
      '/vedetos/Paulo/Paulo 0.png',
      '/vedetos/Paulo/Paulo 1.png',
      '/vedetos/Paulo/Paulo 2.png',
      '/vedetos/Paulo/Paulo 3.png',
      '/vedetos/Paulo/Paulo 4.png',
      '/vedetos/Paulo/Paulo 5.png',
      '/vedetos/Paulo/Paulo 6.png',
      '/vedetos/Paulo/Paulo 7.png',
    ],
    rating: 4.82,
    reviewCount: 67,
    pricing: PRICING,
    availability: generateAvailability(),
    location: 'Santiago, Chile',
    specialties: ['Capitan', 'Vaquero', 'Militar'],
    featured: true,
  },
  {
    id: '10',
    name: 'Lazaro',
    slug: 'lazaro',
    shortDescription: 'Presencia magnética y carisma que llena el espacio. Un artista que convierte cada show en un momento irrepetible.',
    fullDescription: 'Lázaro es el artista que equilibra impacto visual y conexión genuina con el público. Su manejo del escenario es preciso y su energía natural eleva el ambiente de cualquier celebración. Cada aparición está construida con cuidado — vestuario, ritmo y actitud coordinados para dejar una huella en cada evento.',
    image: '/vedetos/Lazaro/Lazaro 0.PNG',
    gallery: [
      '/vedetos/Lazaro/Lazaro 0.PNG',
      '/vedetos/Lazaro/Lazaro 1.PNG',
      '/vedetos/Lazaro/Lazaro 2.PNG',
      '/vedetos/Lazaro/Lazaro 3.PNG',
      '/vedetos/Lazaro/Lazaro 4.PNG',
      '/vedetos/Lazaro/Lazaro 5.PNG',
      '/vedetos/Lazaro/Lazaro 6.PNG',
      '/vedetos/Lazaro/Lazaro 7.PNG',
    ],
    rating: 4.8,
    reviewCount: 72,
    pricing: PRICING,
    availability: generateAvailability(),
    location: 'Santiago, Chile',
    specialties: ['Militar', 'Policia', 'Constructor'],
    featured: true,
  },
  {
    id: '12',
    name: 'Adonis',
    slug: 'adonis',
    shortDescription: 'Nombre que lo dice todo. Presencia imponente, carisma natural y un show que eleva el nivel de cualquier celebración.',
    fullDescription: 'Adonis llega con una propuesta que equilibra impacto visual y conexión genuina. Su porte y seguridad en escena generan una atmósfera única desde el primer momento. Cada aparición está construida con precisión — vestuario, ritmo y actitud coordinados para dejar una huella en cada evento.',
    image: '/vedetos/Adonis/Adonis0.PNG',
    gallery: [
      '/vedetos/Adonis/Adonis0.PNG',
      '/vedetos/Adonis/Adonis1.PNG',
      '/vedetos/Adonis/Adonis2.PNG',
      '/vedetos/Adonis/Adonis3.PNG',
      '/vedetos/Adonis/Adonis4.PNG',
      '/vedetos/Adonis/Adonis5.PNG',
    ],
    rating: 4.83,
    reviewCount: 61,
    pricing: PRICING,
    availability: generateAvailability(),
    location: 'Santiago, Chile',
    specialties: ['Militar', 'Constructor', 'Vaquero'],
    featured: true,
  },
  {
    id: '9',
    name: 'Remjo',
    slug: 'remjo',
    shortDescription: 'El perfil más singular del elenco. Estilo oscuro, puesta en escena sofisticada y una atmósfera que no se olvida.',
    fullDescription: 'Remjo construye sus shows desde otra lógica. Su estilo, deliberadamente contenido y sofisticado, genera una tensión escénica que eleva el tono de cualquier evento. Para anfitrionas que buscan algo fuera de lo convencional — una experiencia donde el ambiente importa tanto como el espectáculo.',
    image: '/vedetos/Remjo/Remjo0.webp',
    gallery: [
      '/vedetos/Remjo/Remjo0.webp',
      '/vedetos/Remjo/remjo 1.jpg',
      '/vedetos/Remjo/remjo 2.jpg',
      '/vedetos/Remjo/remjo 3.jpg',
      '/vedetos/Remjo/remjo 4.jpg',
      '/vedetos/Remjo/remjo 5.jpg',
    ],
    rating: 4.78,
    reviewCount: 49,
    pricing: PRICING,
    availability: generateAvailability(),
    location: 'Santiago, Chile',
    specialties: ['Vaquero', 'Policia'],
    featured: true,
  },
]

function generateAvailability(): AvailabilitySlot[] {
  const availability: AvailabilitySlot[] = []
  const today = new Date()
  const allTimes = ['10:00', '14:00', '18:00', '20:00']

  for (let i = 0; i < 60; i++) {
    const date = new Date(today)
    date.setDate(today.getDate() + i)
    const dateStr = date.toISOString().split('T')[0]
    const dayOfWeek = date.getDay()
    const isAvailable = dayOfWeek !== 0 && i % 10 !== 3
    availability.push({
      date: dateStr,
      available: isAvailable,
      times: isAvailable ? allTimes.filter((_, ti) => (i + ti) % 3 !== 0) : [],
    })
  }

  return availability
}

export const featuredVedetos = vedetos.filter(v => v.featured)
